(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.VisaCheckV1Report=api;})(globalThis,function(){
'use strict';
const labels={
SCHENGEN_TRAVEL_DOCUMENT_REMAINING_VALIDITY:'Passport validity after departure',SCHENGEN_TRAVEL_DOCUMENT_MAX_AGE:'Passport age at lodging',SCHENGEN_TRAVEL_DOCUMENT_BLANK_PAGES:'Blank passport pages',SCHENGEN_SHORT_STAY_90_IN_180:'Schengen rolling stay limit',FRANCE_IE_APPLICATION_JURISDICTION:'Application jurisdiction and legal residence',FRANCE_IE_IRP_DOCUMENT_PRESENCE:'Irish residence card',FRANCE_IE_IRP_POST_RETURN_VALIDITY:'IRP validity after return',SCHENGEN_INSURANCE_PRESENCE:'Travel medical insurance',SCHENGEN_INSURANCE_COVERAGE_AMOUNT:'Insurance coverage amount',SCHENGEN_INSURANCE_DATE_COVERAGE:'Insurance dates',SCHENGEN_INSURANCE_TERRITORY:'Insurance territory',SCHENGEN_INSURANCE_MEDICAL_REPATRIATION:'Medical repatriation cover',SCHENGEN_INSURANCE_EMERGENCY_OR_HOSPITAL_COVERAGE:'Emergency medical or hospital cover',SCHENGEN_EARLIEST_LODGING:'Earliest application date',SCHENGEN_INSURANCE_EVIDENCE:'Insurance evidence',SCHENGEN_ACCOMMODATION_EVIDENCE:'Accommodation evidence',SCHENGEN_FINANCIAL_EVIDENCE:'Financial evidence',SCHENGEN_RETURN_FUNDS_EVIDENCE:'Return travel funds',SCHENGEN_RETURN_ONWARD_EVIDENCE:'Return or onward travel evidence',SCHENGEN_ITINERARY_EVIDENCE:'Travel itinerary',SCHENGEN_PURPOSE_EVIDENCE:'Purpose evidence',SCHENGEN_INTENTION_INFORMATION:'Intention-to-leave information',FRANCE_PRIVATE_HOST_ORIGINAL_ATTESTATION:'Original private-host attestation',APPLICATION_FORM:'Application form',APPLICATION_RECEIPT:'Application receipt',PASSPORT_ORIGINAL:'Passport original',PASSPORT_COPY:'Passport copy',IDENTITY_PHOTOS:'Identity photos',SUPPORTING_DOCUMENT_SET:'Supporting originals and copies',ONLINE_FORM:'France-Visas form',ONLINE_VALIDATION:'Online validation',APPOINTMENT:'Appointment',FILE_ASSERTION:'Personal checklist review',SUBMISSION:'Submission',PASSPORT_RETURN:'Passport return envelope',SCHENGEN_BIOMETRICS_PROCEDURE:'Biometrics',IRELAND_RETURN_DOCUMENT_READINESS:'Return to Ireland',FRANCE_SHORT_STAY_PURPOSES:'Purpose route'};
const reasons={NEW_COLLECTION_REQUIRED:'A new biometric collection is needed; follow the appointment instructions.',POTENTIAL_REUSE_REQUIRES_CONFIRMATION:'Previous collection is within the configured reuse window, but reuse still needs confirmation.',REUSE_REPORTED_CONFIRMED:'You reported confirmed reuse. This does not establish an attendance exemption.',SPECIAL_BIOMETRIC_HANDLING_REQUIRED:'Special biometric handling requires contact with the application service.',AGE_BOUNDARY_REQUIRES_REVIEW:'The age boundary remains under review.',VALID_CARD_ON_RETURN:'The supplied card is valid on the return date under this diagnostic.',VALID_RETURN_DOCUMENT_REQUIRED:'Return documentation needs action. A pending renewal is not treated as a valid card.',RETURN_DOCUMENT_REQUIRES_REVIEW:'Return documentation needs review.',SPECIAL_OR_DIFFERENT_ROUTE_REQUIRED:'The supplied facts need a different or special route.',UNRESOLVED_ROUTE_DURATION:'Trip dates are needed to determine purpose-route scope.'};
const label=r=>labels[r.rule_id||r.evidence_id||r.procedure_id||r.configuration_id||r.diagnostic_id]||'Requirement check';
function message(r){
 if(reasons[r.reason])return reasons[r.reason];
 const state=r.status||r.classification;
 if(state==='UNKNOWN'){
 const unknown=Object.entries(r.relevant_facts||{}).filter(([,f])=>f.state!=='KNOWN').map(([p])=>p.split('.').at(-1).replaceAll('_',' '));
 return unknown.length?'We could not determine this. Missing or invalid information: '+[...new Set(unknown)].join(', ')+'.':'This needs more information or review; it is not a failure.';
 }
 return {PASS:'The supplied facts meet this configured requirement.',FAIL:'The supplied facts do not meet this configured requirement. This is not a visa decision.',PRESENT:'Document/evidence reported present; acceptance still requires assessment.',MISSING:'Document/action appears outstanding. This does not predict visa refusal.',NOT_APPLICABLE:'This check does not apply to the supplied facts.',READY:'This preparation step is reported ready.',ACTION_REQUIRED:'An application or document action remains outstanding.',SUPPORTED:'This purpose is covered by the configured preview route.'}[state]||'Review this information with the application authority.';
}
function render(target,report,sources,community){
 target.replaceChildren();
 const el=(tag,text,parent=target)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;parent.append(n);return n;};
 const section=title=>{const n=el('section');n.className='report-section';el('h3',title,n);return n;};
 const sourceLinks=(r,parent)=>{for(const ref of r.source_refs||[]){const s=sources[ref.path];if(s&&/^https:\/\//.test(s.url||'')){const a=el('a','Official source: '+s.title+' (verification pending)',parent);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';a.className='source-link';}}};
 const row=(r,parent)=>{const n=el('article',undefined,parent);n.className='result-row';el('h4',label(r),n);const badge=el('span',(r.status||r.classification||'UNKNOWN').replaceAll('_',' '),n);badge.className='status status-'+(r.status||r.classification||'UNKNOWN');el('p',message(r),n);if(r.requirement)el('p',r.requirement,n);
 if(r.evidence_status==='EVIDENCE_REFRESH_REQUIRED')el('p','Current process — verification pending.',n);
 if(r.evidence_id==='SCHENGEN_INTENTION_INFORMATION')el('p','Intention to leave requires consular assessment; presence is not a credibility determination.',n);
 for(const d of r.diagnostics||[])if(d.code==='EVIDENCE_DATE_COVERAGE')el('p','Evidence date coverage: '+(d.coverage||'UNKNOWN').replaceAll('_',' ')+'.',n);
 sourceLinks(r,n);const debug=el('details',undefined,n);el('summary','Technical details',debug);el('pre',JSON.stringify(r,null,2),debug);return n;};
 el('h2','Visa Check Report');el('p','V1 development preview — evidence has not been independently verified for production.');
 const route=section('1. Route coverage');el('p',report.route.status+' — '+report.route.reason,route);
 const f=report.facts;const names={IN:'India',IE:'Ireland',FR:'France',ES:'Spain',GB:'United Kingdom',metropolitan_france:'Metropolitan France',short_stay:'Short stay',tourism:'Tourism',private_visit:'Private visit'};
 el('p',[report.route.route_id.split(':')[0],f.residence.country,f.trip.destination_country==='FR'?f.trip.destination_territory:f.trip.destination_country,f.trip.visa_type,f.trip.purpose].map(v=>names[v]||v||'Unknown').join(' → '),route);
 el('p','Your travel dates: '+(f.trip.intended_entry_date||'Unknown')+' to '+(f.trip.intended_exit_date||'Unknown')+'. Return to Ireland: '+(f.trip.intended_return_to_ireland_date||'Unknown')+'.',route);
 if(f.trip.destination_country==='FR'&&!f.application.competent_state)el('p','Application jurisdiction needs review: France-only routing has not been established.',route);
 for(const a of report.route.assumptions)el('p',a,route);
 if(report.issues.length)el('p','Some inputs were malformed or conflicting and remain unknown. Correct them in the form.',route);
 const visa=section('2. Visa requirement');el('p',({ANNEX_I_VISA_REQUIRED:'Visa required — nationality baseline',ANNEX_II_VISA_EXEMPT:'Visa exempt — nationality baseline',UNKNOWN:'Unknown'})[report.baseline?.classification]||'Not evaluated for this route.',visa);el('p','Nationality baseline only; this is not an approval or refusal decision.',visa);if(report.baseline)sourceLinks(report.baseline,visa);
 const checks=section('3. Official requirement checks');
 const groups=[['Passport',r=>r.rule_id.includes('TRAVEL_DOCUMENT')],['Stay',r=>r.rule_id.includes('90_IN_180')],['Irish residence',r=>r.rule_id.startsWith('FRANCE_IE')],['Insurance',r=>r.rule_id.includes('INSURANCE')],['Application timing',r=>r.rule_id.includes('LODGING')]];
 for(const [name,filter] of groups){const items=report.legal.filter(filter);if(items.length){el('h4',name,checks);items.forEach(r=>row(r,checks));}}
 const docs=section('4. Document checklist');el('p','Non-exhaustive. Use your personal France-Visas list; document presence does not establish acceptance.',docs);
 for(const [name,filter] of [['Supporting evidence',r=>r.evidence_id.startsWith('SCHENGEN_')],['Application file and private host',r=>!r.evidence_id.startsWith('SCHENGEN_')]]){const items=report.documents.filter(filter);if(items.length){el('h4',name,docs);items.forEach(r=>row(r,docs));}}
 const proc=section('5. Application procedure');if(report.purpose)row(report.purpose,proc);if(report.biometrics)row(report.biometrics,proc);
 for(const r of report.procedure?.items||[])row({...r,source_refs:report.procedure.source_refs,evidence_status:['PASSPORT_RETURN','ONLINE_FORM','FILE_ASSERTION'].includes(r.procedure_id)?'EVIDENCE_REFRESH_REQUIRED':null},proc);
 if(report.procedure){el('p','Visa decision authority: '+report.procedure.decision_authority+'. Appointment/intake provider: '+report.procedure.intake_provider.name+' — current process, verification pending.',proc);el('p',report.procedure.translation_diagnostic==='TRANSLATION_MAY_BE_REQUIRED'?'Translation into French may be requested; acceptance requires review.':report.procedure.translation_diagnostic==='UNKNOWN'?'Translation needs are unknown.':'No language trigger identified from your declared languages.',proc);
 el('h4','Operational guidance — separate from legal results',proc);
 for(const info of report.procedure.operational_information){let text=info.kind==='OPERATIONAL_RECOMMENDATION'?`Recommended lead time: ${info.amount} working days. No deadline has been calculated.`:info.kind==='OPERATIONAL_ESTIMATE'?`Processing estimate: ${info.minimum}–${info.maximum} working days. Delays can occur; this is not guaranteed.`:info.code==='LATEST_LODGING_REQUIRES_REVIEW'?'Latest application timing remains under review; the earliest-lodging check does not establish that you are applying in time.':`Current passport return process — verification pending: ${info.currency} ${info.amount} stamped addressed envelope. Normal in-person collection is not reported available. Rejection handling differs; details need confirmation.`;el('p',text,proc);sourceLinks(info,proc);}}
 const back=section('6. Return to Ireland');if(report.irish_return)row(report.irish_return,back);else el('p','Not evaluated for this route.',back);
 const attention=section('7. Items needing attention');if(!report.attention.length)el('p',report.route.status==='UNSUPPORTED'?'This route is outside preview coverage.':'No outstanding evaluated items in the listed categories. This is not an overall visa verdict.',attention);
 for(const item of report.attention)el('p',item.section+': '+label(item.result)+' — '+(item.section==='Assessment'?'Consular assessment remains required.':message(item.result)),attention);
 const comm=section('8. Community outcome data');el('p','Historical/community-based; not an official decision or guarantee. Available samples may be small or unrepresentative.',comm);
 el('p',community?.message||'Community data unavailable. Official checks remain independent.',comm);
 for(const r of community?.reasons||[])el('p',r.reason+' ('+r.count+' cases)',comm);
 if(community?.issues?.length)el('p',community.issues.length+' dataset validation issue(s); ambiguous fields were retained as unknown.',comm);
 const limits=section('9. Important limitations');el('p','V1 covers a narrow ordinary-adult tourism route. Private visits have partial coverage. The checklist is non-exhaustive; the consular authority decides the visa application. Operational guidance can change. Evidence review, source verification and resolution of known gaps remain outstanding. Community statistics do not override official checks.',limits);
}
return {label,message,render};
});
