const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const fields=require('../../js/v1-form-fields.js');const {adapt}=require('../../js/rules/v1-form-adapter.js');const {evaluate,resolve}=require('../../js/rules/v1-integration.js');
const config=require('../../data/official-requirements/integration/v1-preview.json');const assets=Object.fromEntries(Object.entries(config.assets).map(([id,p])=>[id,JSON.parse(fs.readFileSync(p,'utf8'))]));
function complete(extra={}){const v=Object.fromEntries(fields.filter(f=>f.type==='boolean').map(f=>[f.id,'yes']));return {...v,nationality:'IN',residence:'IE',legal:'yes',age:'30',origin_details:'yes',origin:'IN',special:'no',document:'ordinary',issue:'2028-01-01',expiry:'2038-01-01',pages:'4',destination:'FR',purpose:'tourism',other_schengen:'no',entry:'2030-06-01',exit:'2030-06-10',return:'2030-06-10',activity:'no',history:'no',irp_expiry:'2031-01-01',renewal:'no',amount:'50000',currency:'EUR',insurance_from:'2030-05-01',insurance_to:'2030-07-01',territorial:'SCHENGEN',accommodation:'HOTEL',accommodation_from:'2030-06-01',accommodation_to:'2030-06-10',bio_date:'2029-01-01',physical:'NOT_DECLARED',exemption:'NOT_DECLARED',submitted:'yes',actual_lodging:'2030-04-01',photos:'2',supporting_prepared:'BOTH',languages:'English',...extra};}
// The new mutually exclusive lodging questions intentionally leave the other
// reference event unknown. Existing evaluator assertions remain in batch tests.
function assertSubmittedRules(r){for(const x of r.legal)assert.equal(x.status,x.rule_id==='SCHENGEN_EARLIEST_LODGING'?'UNKNOWN':'PASS',x.rule_id+': '+x.reason);}

const adapter=v=>adapt(v,fields,config),run=v=>evaluate(adapter(v),config,assets);
const legal=(r,id)=>r.legal.find(x=>x.rule_id===id);const doc=(r,id)=>r.documents.find(x=>x.evidence_id===id);
test('V1 adapter preserves blanks, false, zero and unsure',()=>{const a=adapter({pages:'0',insurance:'no',activity:'unsure'});assert.equal(a.model.facts.passport.blank_pages,0);assert.equal(a.model.facts.supporting_evidence.travel_medical_insurance.present,false);assert.equal(a.model.facts.trip.professional_activity_planned,null);assert.equal(a.model.facts.passport.expiry_date,null);assert.equal(a.model.facts.identity.applicant_conditions,null);});
test('V1 adapter validates dates and never substitutes intended for actual lodging',()=>{const a=adapter({submitted:'no',expiry:'2030-02-30',entry:'2030-06-01',intended_lodging:'2030-04-01'});assert.equal(a.model.facts.passport.expiry_date,null);assert.ok(a.model.issues.some(i=>i.path==='passport.expiry_date'));assert.equal(a.model.facts.trip.intended_entry_date,'2030-06-01');assert.equal(a.model.facts.application.lodging_date,null);});
test('V1 history NONE, COMPLETE, INCOMPLETE, unknown authorization and unknown history',()=>{assert.equal(adapter({history:'no'}).model.facts.trip.stay_history_status,'NONE');const v={history:'yes',history_complete:'yes',stays:[{entry_date:'2030-01-01',exit_date:'2030-01-02',authorization_type:'SHORT_STAY'}]};assert.equal(adapter(v).model.facts.trip.stay_history_status,'COMPLETE');v.stays[0].exit_date='';assert.equal(adapter(v).model.facts.trip.stay_history_status,'INCOMPLETE');assert.equal(adapter({history:'yes',history_complete:'yes',stays:[]}).model.facts.trip.stay_history_status,'INCOMPLETE');assert.equal(adapter({history:'unsure'}).model.facts.trip.stay_history_status,'UNKNOWN');});
test('V1 no unapproved nationality or document aliases change classifications',()=>{for(const extra of [{nationality:'Indian'},{document:'normal'}])assert.notEqual(run(complete(extra)).route.status,'SUPPORTED');assert.equal(adapter({}).model.facts.travel.irish_entry_visa_requirement_status,null);});
test('V1 route coverage for identities, private visits and multi-country constraints',()=>{assert.equal(resolve(adapter(complete()),config).status,'SUPPORTED');assert.equal(run(complete({purpose:'private_visit'})).route.status,'PARTIAL');for(const e of [{destination:'ES'},{residence:'GB'},{nationality:'OTHER'},{document:'diplomatic'},{special:'yes'},{age:'11'},{special:'yes'}])assert.equal(run(complete(e)).route.status,'UNSUPPORTED');const multi=run(complete({other_schengen:'yes'}));assert.equal(multi.route.status,'PARTIAL');assert.equal(multi.facts.application.competent_state,null);assert.ok(!multi.legal.some(r=>r.rule_id.startsWith('FRANCE_')));assert.equal(multi.procedure,null);});
test('V1 A complete tourism file keeps all outputs independent',()=>{const r=run(complete());assert.equal(r.route.status,'SUPPORTED');assert.equal(r.baseline.classification,'ANNEX_I_VISA_REQUIRED');assert.ok(r.legal.length>=14);assertSubmittedRules(r);assert.ok(r.documents.every(x=>['PRESENT','NOT_APPLICABLE'].includes(x.status)));assert.equal(r.biometrics.status,'READY');assert.ok(r.procedure.items.every(x=>x.status==='READY'));assert.equal(r.irish_return.status,'READY');assert.equal(r.overall,undefined);});
test('V1 B IRP post-return fail is separate from Irish return readiness',()=>{const r=run(complete({irp_expiry:'2030-06-25'}));assert.equal(legal(r,'FRANCE_IE_IRP_POST_RETURN_VALIDITY').status,'FAIL');assert.equal(r.irish_return.status,'READY');});
test('V1 C passport failure does not alter insurance',()=>{const r=run(complete({expiry:'2030-07-01'}));assert.equal(legal(r,'SCHENGEN_TRAVEL_DOCUMENT_REMAINING_VALIDITY').status,'FAIL');assert.equal(legal(r,'SCHENGEN_INSURANCE_COVERAGE_AMOUNT').status,'PASS');});
test('V1 D rolling-stay violation is evaluated by existing engine',()=>{const r=run(complete({history:'yes',history_complete:'yes',stays:[{entry_date:'2030-01-01',exit_date:'2030-03-31',authorization_type:'SHORT_STAY'}]}));assert.equal(legal(r,'SCHENGEN_SHORT_STAY_90_IN_180').status,'FAIL');assert.equal(legal(r,'SCHENGEN_TRAVEL_DOCUMENT_BLANK_PAGES').status,'PASS');});
test('V1 E missing readiness and appointment never become legal FAIL',()=>{const r=run(complete({finance:'no',sponsor:'no',accommodation_evidence:'no',accommodation_means:'no',appointment:'no'}));assert.equal(doc(r,'SCHENGEN_FINANCIAL_EVIDENCE').status,'MISSING');assert.equal(doc(r,'SCHENGEN_ACCOMMODATION_EVIDENCE').status,'MISSING');assert.equal(r.procedure.items.find(x=>x.procedure_id==='APPOINTMENT').status,'ACTION_REQUIRED');assertSubmittedRules(r);});
test('V1 F missing dates remain UNKNOWN, not FAIL',()=>{const r=run(complete({expiry:'',actual_lodging:'',entry:'',irp_expiry:'',insurance_from:''}));assert.ok(r.legal.some(x=>x.status==='UNKNOWN'));assert.ok(!r.legal.some(x=>x.status==='FAIL'));});
test('V1 G private visit is partial and tourism insurance stays inapplicable',()=>{const r=run(complete({purpose:'private_visit'}));assert.equal(r.route.status,'PARTIAL');assert.ok(r.legal.filter(x=>x.rule_id.includes('INSURANCE')).every(x=>x.status==='NOT_APPLICABLE'));});
test('V1 H Spain unsupported produces no France conclusions',()=>{const r=run(complete({destination:'ES'}));assert.equal(r.route.status,'UNSUPPORTED');assert.equal(r.legal.length,0);assert.equal(r.documents.length,0);assert.equal(r.procedure,null);assert.equal(r.baseline,null);});
test('V1 private host is independent from tourism purpose',()=>{const r=run(complete({accommodation:'PRIVATE_HOST',attestation_original:'no'}));assert.equal(r.route.status,'SUPPORTED');assert.equal(doc(r,'FRANCE_PRIVATE_HOST_ORIGINAL_ATTESTATION').status,'MISSING');});
test('V1 source metadata, draft publication, attention ordering and no combined score',()=>{const r=run(complete({expiry:'2030-07-01',finance:'no',sponsor:'no'}));assert.ok(r.legal.every(x=>Array.isArray(x.source_refs)));assert.ok(r.legal.every(x=>x.publication.release_ready===false));assert.equal(r.attention[0].priority,1);assert.ok(r.attention.every((x,i,a)=>!i||x.priority>=a[i-1].priority));assert.equal(r.score,undefined);});
test('V1 browser module load order works without CommonJS',()=>{const context=vm.createContext({});const html=fs.readFileSync('check.html','utf8');for(const [,file] of html.matchAll(/<script src="([^"]+)"/g)){if(file==='js/checker.js')continue;vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});}assert.equal(typeof context.VisaCheckV1Integration.evaluate,'function');const report=vm.runInContext(`VisaCheckV1Integration.evaluate(VisaCheckV1Adapter.adapt(${JSON.stringify(complete())},VisaCheckV1Fields,${JSON.stringify(config)}),${JSON.stringify(config)},${JSON.stringify(assets)})`,context);assert.equal(report.route.status,'SUPPORTED');assertSubmittedRules(report);});
test('V1 presentation uses readable messages and unknown differs from failure',()=>{const api=require('../../js/v1-report.js');assert.match(api.message({status:'UNKNOWN',relevant_facts:{'passport.expiry_date':{state:'MISSING'}}}),/expiry date/);assert.match(api.message({status:'MISSING'}),/outstanding/);assert.doesNotMatch(api.label({rule_id:'SCHENGEN_TRAVEL_DOCUMENT_MAX_AGE'}),/_/);});
